# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Ayarlar_Kamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayarlar_Kamera(object):
    def setupUi(self, Ayarlar_Kamera):
        Ayarlar_Kamera.setObjectName("Ayarlar_Kamera")
        Ayarlar_Kamera.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Ayarlar_Kamera)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(580, 530, 171, 51))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 30, 251, 141))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        Ayarlar_Kamera.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ayarlar_Kamera)
        QtCore.QMetaObject.connectSlotsByName(Ayarlar_Kamera)

    def retranslateUi(self, Ayarlar_Kamera):
        _translate = QtCore.QCoreApplication.translate
        Ayarlar_Kamera.setWindowTitle(_translate("Ayarlar_Kamera", "Ayarlar_Kamera"))
        self.pushButton.setText(_translate("Ayarlar_Kamera", "Kaydet"))
        self.label.setText(_translate("Ayarlar_Kamera", "Kamera Adet Sayısı:"))
        self.label_2.setText(_translate("Ayarlar_Kamera", "Kamera IP Adresi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ayarlar_Kamera = QtWidgets.QMainWindow()
    ui = Ui_Ayarlar_Kamera()
    ui.setupUi(Ayarlar_Kamera)
    Ayarlar_Kamera.show()
    sys.exit(app.exec_())
