# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ayarlar(object):
    def setupUi(self, Ayarlar):
        Ayarlar.setObjectName("Ayarlar")
        Ayarlar.resize(800, 608)
        self.centralwidget = QtWidgets.QWidget(Ayarlar)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Kamera = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kamera.setGeometry(QtCore.QRect(50, 50, 161, 61))
        self.btn_Kamera.setObjectName("btn_Kamera")
        self.btn_Yazici = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Yazici.setGeometry(QtCore.QRect(50, 150, 161, 61))
        self.btn_Yazici.setObjectName("btn_Yazici")
        self.btn_PLC = QtWidgets.QPushButton(self.centralwidget)
        self.btn_PLC.setGeometry(QtCore.QRect(310, 40, 131, 61))
        self.btn_PLC.setObjectName("btn_PLC")
        self.btn_DataBase = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DataBase.setGeometry(QtCore.QRect(310, 150, 131, 61))
        self.btn_DataBase.setObjectName("btn_DataBase")
        Ayarlar.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ayarlar)
        QtCore.QMetaObject.connectSlotsByName(Ayarlar)

    def retranslateUi(self, Ayarlar):
        _translate = QtCore.QCoreApplication.translate
        Ayarlar.setWindowTitle(_translate("Ayarlar", "Ayarlar"))
        self.btn_Kamera.setText(_translate("Ayarlar", "Kamera"))
        self.btn_Yazici.setText(_translate("Ayarlar", "YAZICI"))
        self.btn_PLC.setText(_translate("Ayarlar", "PLC"))
        self.btn_DataBase.setText(_translate("Ayarlar", "Data Base"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ayarlar = QtWidgets.QMainWindow()
    ui = Ui_Ayarlar()
    ui.setupUi(Ayarlar)
    Ayarlar.show()
    sys.exit(app.exec_())
