# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1779, 1158)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(143, 143, 191);\n"
"border:none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QToolTip{\n"
"    background-color: rgb(143, 143, 191);\n"
"    color: rgb(255, 255, 255) ; \n"
"    font: 85 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetButtonMenuButtons = QtWidgets.QWidget(self.centralwidget)
        self.widgetButtonMenuButtons.setMinimumSize(QtCore.QSize(45, 0))
        self.widgetButtonMenuButtons.setMaximumSize(QtCore.QSize(45, 16777215))
        self.widgetButtonMenuButtons.setStyleSheet("background-color: rgb(101, 101, 135);\n"
"border:none;\n"
"border-top-right-radius : 20px;\n"
"border-bottom-right-radius : 20px;")
        self.widgetButtonMenuButtons.setObjectName("widgetButtonMenuButtons")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetButtonMenuButtons)
        self.gridLayout_2.setContentsMargins(3, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.pushButtonSwitchTopageSettings = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSwitchTopageSettings.sizePolicy().hasHeightForWidth())
        self.pushButtonSwitchTopageSettings.setSizePolicy(sizePolicy)
        self.pushButtonSwitchTopageSettings.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonSwitchTopageSettings.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSwitchTopageSettings.setFont(font)
        self.pushButtonSwitchTopageSettings.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/settings_icon.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}")
        self.pushButtonSwitchTopageSettings.setText("")
        self.pushButtonSwitchTopageSettings.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSwitchTopageSettings.setObjectName("pushButtonSwitchTopageSettings")
        self.gridLayout_2.addWidget(self.pushButtonSwitchTopageSettings, 9, 0, 1, 1)
        self.pushButtonSwitchTopageDatabase = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        self.pushButtonSwitchTopageDatabase.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonSwitchTopageDatabase.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButtonSwitchTopageDatabase.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/database.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButtonSwitchTopageDatabase.setText("")
        self.pushButtonSwitchTopageDatabase.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSwitchTopageDatabase.setObjectName("pushButtonSwitchTopageDatabase")
        self.gridLayout_2.addWidget(self.pushButtonSwitchTopageDatabase, 2, 0, 1, 1)
        self.pushButtonSwitchTopageMain = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        self.pushButtonSwitchTopageMain.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonSwitchTopageMain.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButtonSwitchTopageMain.setStyleSheet("QPushButton{\n"
"        qproperty-icon: url(:/ikonlar/icons/plc_icon.png);\n"
"        background-color: rgb(130, 130, 173);\n"
"        border:5px solid rgb(130, 130, 173);\n"
"        border-left-color: rgb(85, 170, 255);\n"
"        border-top-right-radius : 10px;\n"
"        border-bottom-right-radius : 10px;\n"
"\n"
"    }\n"
"QPushButton::hover\n"
"{\n"
"        background-color: rgb(130, 130, 173);\n"
"        border:5px solid rgb(130, 130, 173);\n"
"        border-left-color: rgb(85, 170, 255);\n"
"        border-top-right-radius : 10px;\n"
"        border-bottom-right-radius : 10px;\n"
"}\n"
"")
        self.pushButtonSwitchTopageMain.setText("")
        self.pushButtonSwitchTopageMain.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSwitchTopageMain.setObjectName("pushButtonSwitchTopageMain")
        self.gridLayout_2.addWidget(self.pushButtonSwitchTopageMain, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 10, 0, 1, 1)
        self.pushButtonClose = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClose.sizePolicy().hasHeightForWidth())
        self.pushButtonClose.setSizePolicy(sizePolicy)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButtonClose.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/close_icon.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonClose.setText("")
        self.pushButtonClose.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_2.addWidget(self.pushButtonClose, 11, 0, 1, 1)
        self.pushButtonButtonMenuToggle = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonButtonMenuToggle.sizePolicy().hasHeightForWidth())
        self.pushButtonButtonMenuToggle.setSizePolicy(sizePolicy)
        self.pushButtonButtonMenuToggle.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonButtonMenuToggle.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonButtonMenuToggle.setFont(font)
        self.pushButtonButtonMenuToggle.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/toggle.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}")
        self.pushButtonButtonMenuToggle.setText("")
        self.pushButtonButtonMenuToggle.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonButtonMenuToggle.setObjectName("pushButtonButtonMenuToggle")
        self.gridLayout_2.addWidget(self.pushButtonButtonMenuToggle, 0, 0, 1, 1)
        self.pushButtonOpenOperatorMenu = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOpenOperatorMenu.sizePolicy().hasHeightForWidth())
        self.pushButtonOpenOperatorMenu.setSizePolicy(sizePolicy)
        self.pushButtonOpenOperatorMenu.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonOpenOperatorMenu.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenOperatorMenu.setFont(font)
        self.pushButtonOpenOperatorMenu.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/person.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}")
        self.pushButtonOpenOperatorMenu.setText("")
        self.pushButtonOpenOperatorMenu.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonOpenOperatorMenu.setCheckable(True)
        self.pushButtonOpenOperatorMenu.setObjectName("pushButtonOpenOperatorMenu")
        self.gridLayout_2.addWidget(self.pushButtonOpenOperatorMenu, 4, 0, 1, 1)
        self.pushButtonSwitchTopageLog = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSwitchTopageLog.sizePolicy().hasHeightForWidth())
        self.pushButtonSwitchTopageLog.setSizePolicy(sizePolicy)
        self.pushButtonSwitchTopageLog.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonSwitchTopageLog.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSwitchTopageLog.setFont(font)
        self.pushButtonSwitchTopageLog.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/attention_icon.png);\n"
"\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButtonSwitchTopageLog.setText("")
        self.pushButtonSwitchTopageLog.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSwitchTopageLog.setObjectName("pushButtonSwitchTopageLog")
        self.gridLayout_2.addWidget(self.pushButtonSwitchTopageLog, 7, 0, 1, 1)
        self.pushButtonOpenLoginMenu = QtWidgets.QPushButton(self.widgetButtonMenuButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOpenLoginMenu.sizePolicy().hasHeightForWidth())
        self.pushButtonOpenLoginMenu.setSizePolicy(sizePolicy)
        self.pushButtonOpenLoginMenu.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonOpenLoginMenu.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOpenLoginMenu.setFont(font)
        self.pushButtonOpenLoginMenu.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/ikonlar/icons/optimak.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-right-radius : 10px;\n"
"    border-bottom-right-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(130, 130, 173);\n"
"}")
        self.pushButtonOpenLoginMenu.setText("")
        self.pushButtonOpenLoginMenu.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonOpenLoginMenu.setCheckable(True)
        self.pushButtonOpenLoginMenu.setObjectName("pushButtonOpenLoginMenu")
        self.gridLayout_2.addWidget(self.pushButtonOpenLoginMenu, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.widgetButtonMenuButtons, 1, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidgetMenuler = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidgetMenuler.sizePolicy().hasHeightForWidth())
        self.stackedWidgetMenuler.setSizePolicy(sizePolicy)
        self.stackedWidgetMenuler.setToolTip("")
        self.stackedWidgetMenuler.setStyleSheet("background-color: rgb(143, 143, 191);\n"
"border:1px solid rgb(0,0,0);\n"
"border:none;")
        self.stackedWidgetMenuler.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidgetMenuler.setObjectName("stackedWidgetMenuler")
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.label_4 = QtWidgets.QLabel(self.pageMain)
        self.label_4.setGeometry(QtCore.QRect(190, 70, 451, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidgetMenuler.addWidget(self.pageMain)
        self.pageDatabase = QtWidgets.QWidget()
        self.pageDatabase.setObjectName("pageDatabase")
        self.label_5 = QtWidgets.QLabel(self.pageDatabase)
        self.label_5.setGeometry(QtCore.QRect(260, 170, 381, 191))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidgetMenuler.addWidget(self.pageDatabase)
        self.pageLog = QtWidgets.QWidget()
        self.pageLog.setObjectName("pageLog")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pageLog)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidgetLog = QtWidgets.QTableWidget(self.pageLog)
        self.tableWidgetLog.setStyleSheet("QTableWidget{\n"
"    border:none;\n"
"}\n"
"\n"
"QHeaderView{\n"
"    border:none;\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(143, 143, 191);\n"
"    border: 2px solid rgb(71, 71, 95);\n"
"    border-radius:5px;\n"
"    padding-left:5px;\n"
"}\n"
"QTableCornerButton::section{\n"
"    background-color: rgb(143, 143, 191);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: rgb(143, 143, 191);\n"
"    width:14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:0px;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"    border: none;\n"
"    background-color: rgb(101, 101, 135);\n"
"    min-height:30px;\n"
"    border-radius:7px;\n"
" }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background-color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(143, 143, 191);\n"
"    height:14px;\n"
"    margin: 0 15px 0 15px;\n"
"    border-radius:0px;\n"
" }\n"
" QScrollBar::handle:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(101, 101, 135);\n"
"    min-width:30px;\n"
"    border-radius:7px;\n"
" }\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background-color: none;\n"
"}")
        self.tableWidgetLog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidgetLog.setObjectName("tableWidgetLog")
        self.tableWidgetLog.setColumnCount(3)
        self.tableWidgetLog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetLog.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.tableWidgetLog, 4, 1, 1, 1)
        self.widgetLogFiltreleri = QtWidgets.QWidget(self.pageLog)
        self.widgetLogFiltreleri.setObjectName("widgetLogFiltreleri")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetLogFiltreleri)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonFiltreleriTemizle = QtWidgets.QPushButton(self.widgetLogFiltreleri)
        self.pushButtonFiltreleriTemizle.setMinimumSize(QtCore.QSize(45, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFiltreleriTemizle.setFont(font)
        self.pushButtonFiltreleriTemizle.setStyleSheet("QPushButton{\n"
"    background-color: rgb(101, 101, 135);\n"
"    qproperty-icon: url(:/ikonlar/icons/clear_icon.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(254,83,53,255);\n"
"\n"
"}\n"
"\n"
"")
        self.pushButtonFiltreleriTemizle.setText("")
        self.pushButtonFiltreleriTemizle.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonFiltreleriTemizle.setObjectName("pushButtonFiltreleriTemizle")
        self.horizontalLayout.addWidget(self.pushButtonFiltreleriTemizle)
        self.lineEditLogFiltreTarih = QtWidgets.QLineEdit(self.widgetLogFiltreleri)
        self.lineEditLogFiltreTarih.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLogFiltreTarih.setFont(font)
        self.lineEditLogFiltreTarih.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 2px solid rgb(71, 71, 95);\n"
"border-radius:10px;")
        self.lineEditLogFiltreTarih.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditLogFiltreTarih.setObjectName("lineEditLogFiltreTarih")
        self.horizontalLayout.addWidget(self.lineEditLogFiltreTarih)
        self.lineEditLogFiltreKaynak = QtWidgets.QLineEdit(self.widgetLogFiltreleri)
        self.lineEditLogFiltreKaynak.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEditLogFiltreKaynak.setFont(font)
        self.lineEditLogFiltreKaynak.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 2px solid rgb(71, 71, 95);\n"
"border-radius:10px;")
        self.lineEditLogFiltreKaynak.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditLogFiltreKaynak.setObjectName("lineEditLogFiltreKaynak")
        self.horizontalLayout.addWidget(self.lineEditLogFiltreKaynak)
        self.lineEditLogFiltreHata = QtWidgets.QLineEdit(self.widgetLogFiltreleri)
        self.lineEditLogFiltreHata.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEditLogFiltreHata.setFont(font)
        self.lineEditLogFiltreHata.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: 2px solid rgb(71, 71, 95);\n"
"border-radius:10px;")
        self.lineEditLogFiltreHata.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditLogFiltreHata.setObjectName("lineEditLogFiltreHata")
        self.horizontalLayout.addWidget(self.lineEditLogFiltreHata)
        self.gridLayout_5.addWidget(self.widgetLogFiltreleri, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonLogFiltreEnable = QtWidgets.QPushButton(self.pageLog)
        self.pushButtonLogFiltreEnable.setMinimumSize(QtCore.QSize(30, 35))
        self.pushButtonLogFiltreEnable.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogFiltreEnable.setFont(font)
        self.pushButtonLogFiltreEnable.setStyleSheet("QPushButton{\n"
"    background-color: rgb(101, 101, 135);\n"
"    qproperty-icon: url(:/ikonlar/icons/filter_icon.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius : 10px;\n"
"}\n"
"QPushButton::checked\n"
"{\n"
"    background-color: rgba(83,254,83,255);\n"
"\n"
"}\n"
"\n"
"")
        self.pushButtonLogFiltreEnable.setText("")
        self.pushButtonLogFiltreEnable.setIconSize(QtCore.QSize(25, 30))
        self.pushButtonLogFiltreEnable.setCheckable(True)
        self.pushButtonLogFiltreEnable.setObjectName("pushButtonLogFiltreEnable")
        self.horizontalLayout_3.addWidget(self.pushButtonLogFiltreEnable)
        self.label_3 = QtWidgets.QLabel(self.pageLog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius: 2px;\n"
"border: 2px solid rgb(71, 71, 95);\n"
"border-bottom-left-radius : 10px;\n"
"border-bottom-right-radius : 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.widgetLogKaydiYokUyarisi = QtWidgets.QWidget(self.pageLog)
        self.widgetLogKaydiYokUyarisi.setObjectName("widgetLogKaydiYokUyarisi")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetLogKaydiYokUyarisi)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widgetLogKaydiYokUyarisi)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgba(254,83,53,255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widgetLogKaydiYokUyarisi, 5, 1, 1, 1)
        self.stackedWidgetMenuler.addWidget(self.pageLog)
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName("pageSettings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageSettings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.pageSettings)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(1107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 0, 1, 1)
        self.pushButtonAyarlarDetay = QtWidgets.QPushButton(self.pageSettings)
        self.pushButtonAyarlarDetay.setMinimumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAyarlarDetay.setFont(font)
        self.pushButtonAyarlarDetay.setStyleSheet("QPushButton{\n"
"    background-color: rgb(187, 221, 255);\n"
"    qproperty-icon: url(:/images/icons/log_out.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(8, 255, 132);\n"
"\n"
"}")
        self.pushButtonAyarlarDetay.setObjectName("pushButtonAyarlarDetay")
        self.gridLayout_3.addWidget(self.pushButtonAyarlarDetay, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 987, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.stackedWidgetMenuler.addWidget(self.pageSettings)
        self.verticalLayout.addWidget(self.stackedWidgetMenuler)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(143, 143, 191);\n"
"border-radius: 10px;\n"
"border: 2px solid  rgb(71, 71, 95);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.statusGostergeBase = QtWidgets.QFrame(self.frame)
        self.statusGostergeBase.setMinimumSize(QtCore.QSize(330, 60))
        self.statusGostergeBase.setMaximumSize(QtCore.QSize(330, 60))
        self.statusGostergeBase.setStyleSheet("border:none;")
        self.statusGostergeBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusGostergeBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusGostergeBase.setObjectName("statusGostergeBase")
        self.statusGostergeProgress = QtWidgets.QFrame(self.statusGostergeBase)
        self.statusGostergeProgress.setGeometry(QtCore.QRect(0, 0, 330, 60))
        self.statusGostergeProgress.setStyleSheet("QFrame{\n"
"    border-radius:10px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, \n"
"stop:0 rgba(0, 172, 255, 0), stop:0.000970874 rgba(0, 156, 211, 255), \n"
"stop:0.262806 rgba(0, 182, 211, 255), stop:0.263033 rgba(0, 0, 255, 0), \n"
"stop:0.500971 rgba(20, 255, 0, 0), stop:0.501942 rgba(20, 255, 0, 255),\n"
" stop:0.760194 rgba(0, 255, 0, 255), stop:0.763033 rgba(0, 255, 0, 0));\n"
"\n"
"}")
        self.statusGostergeProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusGostergeProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusGostergeProgress.setObjectName("statusGostergeProgress")
        self.statusGostergeBg = QtWidgets.QFrame(self.statusGostergeBase)
        self.statusGostergeBg.setGeometry(QtCore.QRect(0, 0, 330, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusGostergeBg.sizePolicy().hasHeightForWidth())
        self.statusGostergeBg.setSizePolicy(sizePolicy)
        self.statusGostergeBg.setStyleSheet("QFrame{\n"
"border-radius:10px;\n"
"background-color: rgba(77, 77, 77,120);\n"
"\n"
"}\n"
"")
        self.statusGostergeBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusGostergeBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusGostergeBg.setObjectName("statusGostergeBg")
        self.statusGostergeContainer = QtWidgets.QFrame(self.statusGostergeBase)
        self.statusGostergeContainer.setGeometry(QtCore.QRect(5, 5, 320, 50))
        self.statusGostergeContainer.setStyleSheet("QFrame{\n"
"    border-radius:10px;\n"
"    background-color: rgb(182, 182, 243);\n"
"}")
        self.statusGostergeContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusGostergeContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusGostergeContainer.setObjectName("statusGostergeContainer")
        self.label_60 = QtWidgets.QLabel(self.statusGostergeContainer)
        self.label_60.setGeometry(QtCore.QRect(0, 3, 320, 44))
        self.label_60.setStyleSheet("image: url(:/ikonlar/icons/optimus_logo_2.png);\n"
"border:none;")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.statusGostergeBg.raise_()
        self.statusGostergeProgress.raise_()
        self.statusGostergeContainer.raise_()
        self.gridLayout_8.addWidget(self.statusGostergeBase, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 4)
        self.widgetSagAcilirMenu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSagAcilirMenu.sizePolicy().hasHeightForWidth())
        self.widgetSagAcilirMenu.setSizePolicy(sizePolicy)
        self.widgetSagAcilirMenu.setMinimumSize(QtCore.QSize(280, 0))
        self.widgetSagAcilirMenu.setMaximumSize(QtCore.QSize(280, 16777215))
        self.widgetSagAcilirMenu.setStyleSheet("background-color: rgb(101, 101, 135);\n"
"border: none;\n"
"border-top-left-radius : 20px;\n"
"border-bottom-left-radius : 20px;")
        self.widgetSagAcilirMenu.setObjectName("widgetSagAcilirMenu")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widgetSagAcilirMenu)
        self.gridLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButtonSagAcilirMenuKapat = QtWidgets.QPushButton(self.widgetSagAcilirMenu)
        self.pushButtonSagAcilirMenuKapat.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSagAcilirMenuKapat.setFont(font)
        self.pushButtonSagAcilirMenuKapat.setStyleSheet("QPushButton{\n"
"    qproperty-icon: url(:/images/icons/left_icon.png);\n"
"    background-color: rgb(101, 101, 135);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonSagAcilirMenuKapat.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonSagAcilirMenuKapat.setObjectName("pushButtonSagAcilirMenuKapat")
        self.gridLayout_15.addWidget(self.pushButtonSagAcilirMenuKapat, 4, 0, 1, 1)
        self.stackedWidgetSagAcilirMenu = QtWidgets.QStackedWidget(self.widgetSagAcilirMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidgetSagAcilirMenu.sizePolicy().hasHeightForWidth())
        self.stackedWidgetSagAcilirMenu.setSizePolicy(sizePolicy)
        self.stackedWidgetSagAcilirMenu.setObjectName("stackedWidgetSagAcilirMenu")
        self.pageGirisCikisYap = QtWidgets.QWidget()
        self.pageGirisCikisYap.setObjectName("pageGirisCikisYap")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageGirisCikisYap)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem10)
        self.label = QtWidgets.QLabel(self.pageGirisCikisYap)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEditKullanici = QtWidgets.QLineEdit(self.pageGirisCikisYap)
        self.lineEditKullanici.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditKullanici.setFont(font)
        self.lineEditKullanici.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(182, 182, 243);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}")
        self.lineEditKullanici.setText("")
        self.lineEditKullanici.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditKullanici.setObjectName("lineEditKullanici")
        self.verticalLayout_3.addWidget(self.lineEditKullanici)
        self.label_11 = QtWidgets.QLabel(self.pageGirisCikisYap)
        self.label_11.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.lineEditSifre = QtWidgets.QLineEdit(self.pageGirisCikisYap)
        self.lineEditSifre.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSifre.setFont(font)
        self.lineEditSifre.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(182, 182, 243);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}")
        self.lineEditSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditSifre.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSifre.setObjectName("lineEditSifre")
        self.verticalLayout_3.addWidget(self.lineEditSifre)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.pushButtonGirisYap = QtWidgets.QPushButton(self.pageGirisCikisYap)
        self.pushButtonGirisYap.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonGirisYap.setFont(font)
        self.pushButtonGirisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/log_in.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"\n"
"}")
        self.pushButtonGirisYap.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonGirisYap.setObjectName("pushButtonGirisYap")
        self.verticalLayout_3.addWidget(self.pushButtonGirisYap)
        spacerItem12 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem12)
        self.pushButtonCikisYap = QtWidgets.QPushButton(self.pageGirisCikisYap)
        self.pushButtonCikisYap.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCikisYap.setFont(font)
        self.pushButtonCikisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/log_out.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonCikisYap.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonCikisYap.setObjectName("pushButtonCikisYap")
        self.verticalLayout_3.addWidget(self.pushButtonCikisYap)
        spacerItem13 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.stackedWidgetSagAcilirMenu.addWidget(self.pageGirisCikisYap)
        self.pageOperatorGirisCikisYap = QtWidgets.QWidget()
        self.pageOperatorGirisCikisYap.setObjectName("pageOperatorGirisCikisYap")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageOperatorGirisCikisYap)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem14)
        self.label_30 = QtWidgets.QLabel(self.pageOperatorGirisCikisYap)
        self.label_30.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_2.addWidget(self.label_30)
        self.comboBoxOperatorKullaniciAdi = QtWidgets.QComboBox(self.pageOperatorGirisCikisYap)
        self.comboBoxOperatorKullaniciAdi.setMinimumSize(QtCore.QSize(0, 35))
        self.comboBoxOperatorKullaniciAdi.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxOperatorKullaniciAdi.setFont(font)
        self.comboBoxOperatorKullaniciAdi.setStyleSheet("background-color: rgb(182, 182, 243);")
        self.comboBoxOperatorKullaniciAdi.setFrame(False)
        self.comboBoxOperatorKullaniciAdi.setModelColumn(0)
        self.comboBoxOperatorKullaniciAdi.setObjectName("comboBoxOperatorKullaniciAdi")
        self.verticalLayout_2.addWidget(self.comboBoxOperatorKullaniciAdi)
        self.label_31 = QtWidgets.QLabel(self.pageOperatorGirisCikisYap)
        self.label_31.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_2.addWidget(self.label_31)
        self.lineEditOperatorSifre = QtWidgets.QLineEdit(self.pageOperatorGirisCikisYap)
        self.lineEditOperatorSifre.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditOperatorSifre.setFont(font)
        self.lineEditOperatorSifre.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(182, 182, 243);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}")
        self.lineEditOperatorSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditOperatorSifre.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOperatorSifre.setObjectName("lineEditOperatorSifre")
        self.verticalLayout_2.addWidget(self.lineEditOperatorSifre)
        spacerItem15 = QtWidgets.QSpacerItem(17, 286, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.pushButtonOperatorGirisYap = QtWidgets.QPushButton(self.pageOperatorGirisCikisYap)
        self.pushButtonOperatorGirisYap.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperatorGirisYap.setFont(font)
        self.pushButtonOperatorGirisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/log_in.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 255, 0);\n"
"\n"
"}")
        self.pushButtonOperatorGirisYap.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonOperatorGirisYap.setObjectName("pushButtonOperatorGirisYap")
        self.verticalLayout_2.addWidget(self.pushButtonOperatorGirisYap)
        spacerItem16 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem16)
        self.pushButtonOperatorCikisYap = QtWidgets.QPushButton(self.pageOperatorGirisCikisYap)
        self.pushButtonOperatorCikisYap.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOperatorCikisYap.setFont(font)
        self.pushButtonOperatorCikisYap.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 170, 255);\n"
"    qproperty-icon: url(:/images/icons/log_out.png);\n"
"    color: rgb(0, 0, 0);\n"
"    border-top-left-radius : 10px;\n"
"    border-bottom-left-radius : 10px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButtonOperatorCikisYap.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonOperatorCikisYap.setObjectName("pushButtonOperatorCikisYap")
        self.verticalLayout_2.addWidget(self.pushButtonOperatorCikisYap)
        spacerItem17 = QtWidgets.QSpacerItem(17, 285, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.comboBoxOperatorKullaniciAdi.raise_()
        self.label_30.raise_()
        self.lineEditOperatorSifre.raise_()
        self.label_31.raise_()
        self.pushButtonOperatorGirisYap.raise_()
        self.pushButtonOperatorCikisYap.raise_()
        self.stackedWidgetSagAcilirMenu.addWidget(self.pageOperatorGirisCikisYap)
        self.gridLayout_15.addWidget(self.stackedWidgetSagAcilirMenu, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widgetSagAcilirMenu, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidgetMenuler.setCurrentIndex(3)
        self.stackedWidgetSagAcilirMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OPTİMUS by Optimak"))
        self.pushButtonSwitchTopageSettings.setToolTip(_translate("MainWindow", "AYARLAR"))
        self.pushButtonSwitchTopageDatabase.setToolTip(_translate("MainWindow", "DATABASE"))
        self.pushButtonSwitchTopageMain.setToolTip(_translate("MainWindow", "PLC SİNYALLER"))
        self.pushButtonSwitchTopageMain.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">PLC HABERLEŞME</span></p></body></html>"))
        self.pushButtonClose.setToolTip(_translate("MainWindow", "PROGRAMI KAPAT"))
        self.pushButtonButtonMenuToggle.setToolTip(_translate("MainWindow", "GÖSTER/GİZLE"))
        self.pushButtonOpenOperatorMenu.setToolTip(_translate("MainWindow", "OPERATÖR"))
        self.pushButtonSwitchTopageLog.setToolTip(_translate("MainWindow", "LOGLAR"))
        self.pushButtonOpenLoginMenu.setToolTip(_translate("MainWindow", "GİRİŞ/ÇIKIŞ"))
        self.label_4.setText(_translate("MainWindow", "SİNYALLER SAYFASI"))
        self.label_5.setText(_translate("MainWindow", "DATABASE"))
        item = self.tableWidgetLog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TARIH"))
        item = self.tableWidgetLog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "KAYNAK"))
        item = self.tableWidgetLog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "HATA"))
        self.label_3.setText(_translate("MainWindow", "LOG SAYFASI"))
        self.label_2.setText(_translate("MainWindow", "LOG KAYDI YOK !"))
        self.label_6.setText(_translate("MainWindow", "AYARLAR SAYFASI"))
        self.pushButtonAyarlarDetay.setText(_translate("MainWindow", "AYARLAR DETAY"))
        self.pushButtonSagAcilirMenuKapat.setText(_translate("MainWindow", "KAPAT"))
        self.label.setText(_translate("MainWindow", "KULLANICI  ADI"))
        self.label_11.setText(_translate("MainWindow", "ŞİFRE   "))
        self.pushButtonGirisYap.setText(_translate("MainWindow", "GİRİŞ YAP"))
        self.pushButtonCikisYap.setText(_translate("MainWindow", "ÇIKIŞ YAP"))
        self.label_30.setText(_translate("MainWindow", "OPERATÖR KULLANICI ADI"))
        self.label_31.setText(_translate("MainWindow", "ŞİFRE"))
        self.pushButtonOperatorGirisYap.setText(_translate("MainWindow", "GİRİŞ YAP"))
        self.pushButtonOperatorCikisYap.setText(_translate("MainWindow", "ÇIKIŞ YAP"))
import ikonlar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
